version: 2

sources:
  - name: snf_staging
    database: SNEAKER_FAQTORY_DB_2  
    description: This is a source for staging shcema, untransformed data
    schema: STAGING  
    tables:
      - name: MAKT
      - name: VCUR
      - name: TCURC
      - name: KONP
      - name: TVKOT
      - name: VBAK