version: 2

sources:
  - name: snf_staging
    database: SNEAKER_FAQTORY_DB_2  
    description: This is a source for staging shcema, untransformed data
    schema: STAGING  
    tables:
      - name: MAKT
      - name: VCUR
      - name: TCURC
      - name: KONP
      - name: TVKOT
      - name: VBAK
      - name: VBRP
      - name: LIPS

models:
  - name: konp
    columns:
      - name: index
        tests:
          - unique
          - not_null

  - name: makt 
    columns:
      - name: index
        tests:
          - unique
          - not_null

  - name: tcurc
    columns:
      - name: index
        tests:
          - unique
          - not_null

  - name: tvkot
    columns:
      - name: PAYMENT_ID
        tests:
          - unique
          - not_null

  - name: vbrp
    columns:
      - name: index
        tests:
          - unique
          - not_null

  - name: vbak
    columns:
      - name: index
        tests:
          - unique
          - not_null

  - name: vcur
    columns:
      - name: index
        tests:
          - unique
          - not_null