version: 2

sources:
  - name: snf_raw
    database: SNEAKER_FAQTORY_DB_2  
    description: This is a source for raw shcema, only nulls and data types handled
    schema: RAW  
    tables:
      - name: MAKT
      - name: VCUR
      - name: TCURC
      - name: KONP
      - name: TVKOT
      - name: VBAK